_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.10
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
batch_size:
    value: 32
device:
    value: cpu
epochs:
    value: 50
learning_rate:
    value: 0.001
model_type:
    value: mobilenetv3
